### ISSUE TITLE
404 Not found on subfolder on shared hosting

### ISSUE THREAD

**Issue by fmineo** [simplemvc/skeleton#2]
Hi
I'm trying to install the application on a shared hosting without composer and in a subfolder.

I created the project locally with composer, then I uploaded to my hosting via FTP.

The application is located at `/home/username/domains/example.com/public_html/project/`, where public_html is the default document root.

Since I cannot change the document root to public/ directory, I created the following .htaccess rule in `public_html/.htaccess`

`DirectoryIndex index.php`
`RewriteEngine On`
`RewriteCond %{SERVER_PORT} 80`
`RewriteRule ^ https://www.example.com%{REQUEST_URI} [R,L]`
`RewriteRule !^project/ /project/public%{REQUEST_URI} [L]`

Now I'm able too see the Home route when the URL is `https://www.example.com` but other routes (/secret or /hello/alberto) returns 404 error.

Is this issure related to the htaccess rule?

How can I run the application if document root cannot be changed? 

Thanks

**Comment by ezimuel** [comment]
@fmineo Thanks for reporting this! We didn't test SimpleMVC on a shared hosts with Apache. I think we need to add an `.htaccess` in the `public` folder of the skeleton app.
We can use a pretty standard one, like as follows:
```
RewriteEngine On

# The following rule tells Apache that if the requested filename
# exists, simply serve it.
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [L]

# The following rewrites all other queries to index.php. The
# condition ensures that if you are using Apache aliases to do
# mass virtual hosting or installed the project in a subdirectory,
# the base path will be prepended to allow proper resolution of
# the index.php file; it will work in non-aliased environments
# as well, providing a safe, one-size fits all solution.
RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
RewriteRule ^(.*) - [E=BASE:%1]
RewriteRule ^(.*)$ %{ENV:BASE}/index.php [L]
```
Then you can try to use your `.htaccess` in the `public_html` folder of your environment. I'm not sure if the actual router logic implemented in `public/index.php` is able to match subfolder. Can you try and let me know?
We will definitely fix this since I guess it's a common issue for all the users of shared hosting.

**Comment by ezimuel** [comment]
@fmineo I just [added](https://github.com/simplemvc/skeleton/commit/319da5002c539eb9401543674b7b820ca081a644) the `.htaccess` file in /public

**Comment by ezimuel** [comment]
The fix has been released in skeleton ver. [0.2](https://github.com/simplemvc/skeleton/releases/tag/0.2)
